ECO/urls.py
from .views import *
from django.conf.urls import url, include

disease_pattern = [
    url(r'^$', disease_index, name='disease_index'),
    url(r'^(?P<disease_id>[0-9]+)/$', disease_detail, name='disease_detail'),
]

symptom_pattern = [
    url(r'^$', symptom_index, name='symptom_index'),
    url(r'^(?P<symptom_id>[0-9]+)/$', symptom_detail, name='symptom_detail'),
]

treatment_pattern = [
    url(r'^$', treatment_index, name='treatment_index'),
    url(r'^(?P<treatment_id>[0-9]+)/$', treatment_detail, name='treatment_detail'),
]

person_pattern = [
    url(r'^$',person_disease,name='person_index'),
    url(r'^person_disease/$',person_disease,name='person_disease'),
    url(r'^person_symptom/$',person_symptom,name='person_symptom'),
    url(r'^person_treatment/$',person_treatment,name='person_treatment'),
    url(r'^person_info/$',person_info,name='person_info'),
    url(r'^person_update/$',person_update,name='person_update'),
    url(r'^person_diagram/$',person_diagram,name='person_diagram'),
]

social_pattern = [
    url(r'^$',social_friendstate, name='social_index'),
    url(r'social_friendstate/$',social_friendstate,name='social_friendstate'),
    url(r'social_friendlist/$',social_friendlist,name='social_friendlist'),
    url(r'social_sendstate/$',social_sendstate,name='social_sendstate'),
    url(r'social_newfriend/$',social_newfriend,name='social_newfriend'),
    url(r'social_heart/$',social_heart,name='social_heart'),
]

app_name = 'ECO'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^user_login$', user_login, name='user_login'),
    url(r'^user_register$', user_register, name='user_register'),
    url(r'^user_logout$', user_logout, name='user_logout'),
    url(r'^disease/', include(disease_pattern)),
    url(r'^treatment/', include(treatment_pattern)),
    url(r'^symptom/', include(symptom_pattern)),
    url(r'^person/', include(person_pattern)),
    url(r'^social/', include(social_pattern)),
]

ECO_Health/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from ECO import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ECO/', include('ECO.urls', namespace='ECO')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG is False:
    # from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    # urlpatterns += staticfiles_urlpatterns()  # django 1.8 以上不需要
    handler404 = views.page_not_found
    handler500 = views.page_error

ECO/models.py
import os
from django.db import models
from django.contrib.auth.models import User
import os
from django.core.files.storage import FileSystemStorage

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

class Disease(models.Model):
    disease_name = models.CharField(max_length=30)
    type = models.CharField(max_length=30)
    disease_infor = models.CharField(max_length=500)
    total_people = models.IntegerField()
    fresh_people = models.IntegerField()

    def __str__(self):
        return self.disease_name


class Symptom(models.Model):
    symptom_name = models.CharField(max_length=30, default=" ")
    symptom_infor = models.CharField(max_length=500, default=" ")
    diseases = models.ManyToManyField(Disease)

    def __str__(self):
        return self.symptom_name


class Treatment(models.Model):
    treatment_name = models.CharField(max_length=30, default=" ")
    treatment_info = models.CharField(max_length=500, blank=True)
    type = models.CharField(max_length=30, default=" ")
    symptoms = models.ManyToManyField(Symptom)

    def __str__(self):
        return self.treatment_name


class Evaluation(models.Model):
    disease = models.ForeignKey(Disease, null=True)
    treatment = models.ForeignKey(Treatment)
    cost = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    choices = (('1', '少于1个月'), ('2', '1-6个月'), ('3', '6-12个月'), ('4', '1年以上'))
    use_time = models.CharField(max_length=2, choices=choices, blank=True)
    negative_score = models.IntegerField(default=0)
    positive_score = models.IntegerField(default=0)
    negative_symptoms = models.ManyToManyField(Symptom)

    def __str__(self):
        return str(str(self.id) + ' ' + self.treatment.treatment_name) + '价格：' + str(self.cost)


class UserInfo(models.Model):
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    fs = FileSystemStorage(location='/media/head')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to=BASE_DIR+'/media/head')
    choice_index = (('F', '女'), ('M', '男'))
    sex = models.CharField(max_length=10, default="M", choices=choice_index)
    age = models.IntegerField()
    area = models.CharField(max_length=30, default=" ")
    person_infor = models.CharField(max_length=300, default=" ")
    diseases = models.ManyToManyField(Disease, blank=True)
    symptoms = models.ManyToManyField(Symptom, blank=True)
    treatments = models.ManyToManyField(Treatment, blank=True)
    evaluations = models.ManyToManyField(Evaluation, blank=True)
    is_diagnosed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Daily(models.Model):
    date = models.DateField()
    sleep = models.CharField(max_length=20, default=" ")
    energe = models.CharField(max_length=20, default=" ")
    appetite = models.CharField(max_length=20, default=" ")
    mood = models.CharField(max_length=20, default=" ")
    weight = models.FloatField()
    exercise_time = models.FloatField()
    user = models.ForeignKey(UserInfo)

    def __str__(self):
        return self.id


class Message(models.Model):
    user = models.ForeignKey(User)
    content = models.TextField()
    like = models.IntegerField(default=0)
    post_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username + self.content[:5] + '...'


class Comment(models.Model):
    user = models.ForeignKey(User)
    content = models.CharField(max_length=200)
    message = models.ForeignKey(Message)
    post_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['post_time']


class Relation(models.Model):
    user1 = models.ForeignKey(User, related_name='user1')
    user2 = models.ForeignKey(User, related_name='user2')

    def __str__(self):
        return  self.user1.username + '  follow  ' + self.user2.username

ECO/views.py
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, render_to_response, \
    HttpResponse, HttpResponseRedirect

import json
from .method import *
from .models import *


@csrf_exempt
def page_not_found(request):
    return render_to_response('404.html')


@csrf_exempt
def page_error(request):
    return render_to_response('500.html')


@csrf_exempt
def index(request):
    # uesr = User.objects.get(username='li')
    # print(uesr.userinfo.image.name)
    return render(request, "ECO/index.html")


@csrf_exempt
def user_login(request):
    if request.method == "POST":
        info = request.POST
        username = info['username']
        password = info['password']
        try:
            User.objects.get(username=username)
        except Exception:
            result = {'status': 'error', 'error_message': 'user_not_exist'}
            return HttpResponse(json.dumps(result), content_type='application/json')
        user = authenticate(request=request, username=username, password=password)
        if user and user.is_active:
            login(request, user)
            try:
                info['remember_me']
            except Exception:
                request.session.set_expiry(0)
            result = {'status': 'success'}
            return HttpResponse(json.dumps(result), content_type='application/json')
        result = {'status': 'error', 'error_message': 'wrong_password'}
        return HttpResponse(json.dumps(result), content_type='application/json')
    else:
        return render_to_response('404.html')


@csrf_exempt
def user_register(request):
    if request.method == "POST":
        info = request.POST
        username = info['username']
        try:
            User.objects.get(username=username)
        except Exception:
            password = info['password']
            email = info['email']
            sex = info['sex']
            age = info['age']
            area = info['area']
            try:
                user = User.objects.create_user(username, email, password)
                user.save()
            except Exception:
                result = {'status': 'error', 'error_message': 'other'}
                return HttpResponse(json.dumps(result), content_type='application/json')
            else:
                UserInfo(user=user, sex=sex, age=age, area=area).save()
                result = {'status': 'success'}
                return HttpResponse(json.dumps(result), content_type='application/json')
        else:
            result = {'status': 'error', 'error_message': 'user_exist'}
            return HttpResponse(json.dumps(result), content_type='application/json')
    else:
        return render_to_response('404.html')


@csrf_exempt
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('ECO:index'))


@csrf_exempt
def symptom_index(request):
    all_symptom = Symptom.objects.all()
    context = {'all_symptom': all_symptom}
    return render(request, 'ECO/symptom_index.html', context)


@csrf_exempt
def symptom_detail(request, symptom_id):
    keys = ['the_symptom', 'disease_and_num', 'treatment_and_evaluations', 'counts']
    values = load_data_for_symptom_page(symptom_id)
    context = dict(zip(keys, values))
    context = calc_symptom_proportion(context)
    return render(request, 'ECO/symptom_detail.html', context)


@csrf_exempt
def disease_index(request):
    all_disease = Disease.objects.all()
    context = {'all_disease': all_disease}
    return render(request, 'ECO/disease_index.html', context)


@csrf_exempt
def disease_detail(request, disease_id):
    keys = ['disease', 'treatments_for_symptoms', 'treatments_for_disease',
            'evaluations', 'ages', 'diagnosed', 'undiagnosed', 'num_men', 'num_women']
    values = load_data_for_disease_page(disease_id)
    context = dict(zip(keys, values))
    context['counts'] = [len(context[keys[1]]), len(context[keys[2]]), len(context[keys[3]])]
    context = calc_disease_proportion(values, context)
    return render(request, 'ECO/disease_detail.html', context)


@csrf_exempt
def treatment_index(request):
    all_treatment = Treatment.objects.all()
    context = {'all_treatment': all_treatment}
    return render(request, 'ECO/treatment_index.html', context)


@csrf_exempt
def treatment_detail(request, treatment_id):
    keys = ['the_treatment', 'target_symptom_and_num', 'num_side',
            'num_effect', 'num_cost', 'num_time', 'negative_symptoms', 'counts']
    values = load_data_for_treatment_page(treatment_id)
    context = dict(zip(keys, values))
    context = calc_treatment_proportion(context)
    return render(request, 'ECO/treatment_detail.html', context)


@csrf_exempt
@login_required
def person_disease(request):
    """person_disease同"""
    user = request.user
    try:
        whole_user = user.userinfo
        disease_id = whole_user.diseases.all()[0].id
    except IndexError:
        return render_to_response('404.html')
    else:
        keys = ['disease', 'treatments_for_symptoms', 'treatments_for_disease',
                'evaluations', 'ages', 'diagnosed', 'undiagnosed', 'num_men', 'num_women']
        values = load_data_for_disease_page(disease_id)
        context = dict(zip(keys, values))
        context = calc_disease_proportion(values, context)
        return render(request, 'ECO/person_disease.html', context)


@csrf_exempt
@login_required
def person_symptom(request):
    user = request.user
    try:
        whole_user = user.userinfo
        disease_id = whole_user.diseases.all()[0].id
    except IndexError:
        return render_to_response('404.html')
    else:
        keys = ['disease', 'treatments_for_symptoms', 'treatments_for_disease',
                'evaluations', 'ages', 'diagnosed', 'undiagnosed', 'num_men', 'num_women']
        values = load_data_for_disease_page(disease_id)
        context = dict(zip(keys, values))
        return render(request, 'ECO/person_symptom.html', context)


@csrf_exempt
@login_required
def person_treatment(request):
    user = request.user
    try:
        whole_user = user.userinfo
        disease_id = whole_user.diseases.all()[0].id
    except IndexError:
        return render_to_response('404.html')
    else:
        keys = ['disease', 'treatments_for_symptoms', 'treatments_for_disease',
                'evaluations', 'ages', 'diagnosed', 'undiagnosed', 'num_men', 'num_women']
        values = load_data_for_disease_page(disease_id)
        context = dict(zip(keys, values))
        context = calc_disease_proportion(values, context)
        return render(request, 'ECO/person_treatment.html', context)


@csrf_exempt
@login_required
def person_info(request):
    return render(request, 'ECO/person_info.html')


@csrf_exempt
@login_required
def person_update(request):
    return render(request, 'ECO/person_update.html')


@csrf_exempt
@login_required
def person_diagram(request):
    return render(request, 'ECO/person_diagram.html')


@csrf_exempt
@login_required
def social_friendstate(request):
    user = request.user

    you_follow_relation = user.user1.all()
    message_list = []
    for f in you_follow_relation:
        follow_user = f.user2
        temps = follow_user.message_set.all()
        img_path = follow_user.userinfo.image.name

        if img_path != '':
            index = follow_user.userinfo.image.name.find('/media')
            img_path = follow_user.userinfo.image.name[index:]

        if len(temps) != 0:
            for temp in temps:
                message_list.append(
                    [follow_user, img_path, temp.content, temp.like, temp.post_time.strftime("%Y-%m-%d %H:%M:%S")])

    message_list = sorted(message_list, key=lambda m: m[4], reverse=True)

    return render(request, 'ECO/social_friendstate.html', {'message_list': message_list})


@csrf_exempt
@login_required
def social_friendlist(request):
    user = request.user

    follow_you_relation = user.user2.all()
    you_follow_relation = user.user1.all()

    index = 1000
    flag = True
    for f in you_follow_relation:
        if f.user2.userinfo.image.name != '':
            index = f.user2.userinfo.image.name.find('/media')
            flag = False
            break
    if flag:
        for f in follow_you_relation:
            if f.user1.userinfo.image.name != '':
                index = f.user1.userinfo.image.name.find('/media')
                break

    you_follow = [[r.user2.userinfo, r.user2.userinfo.image.name[index:], r.user2.userinfo.age,
                   r.user2.userinfo.diseases.all()[0]] for r in you_follow_relation]
    follow_you = [[r.user1.userinfo, r.user1.userinfo.image.name[index:], r.user1.userinfo.age,
                   r.user1.userinfo.diseases.all()[0]] for r in follow_you_relation]

    context = {'you_follow': you_follow, 'follow_you': follow_you}
    return render(request, 'ECO/social_friendlist.html', context)


@csrf_exempt
@login_required
def social_sendstate(request):
    return render(request, 'ECO/social_sendstate.html')


@csrf_exempt
@login_required
def social_newfriend(request):
    user = request.user
    username = user.username

    disease = user.userinfo.diseases.all()[0]
    symptoms = user.userinfo.symptoms.all()
    treatments = user.userinfo.treatments.all()

    people_by_disease = []
    for p in disease.userinfo_set.all():
        if p.user.username != username:
            img_path = p.image.name
            if p.image.name != '':
                index = p.image.name.find('/media')
                img_path = p.image.name[index:]
            age = p.age
            name = p.user.username
            disease_name = disease.disease_name
            temp = [img_path, name, age, disease_name]
            people_by_disease.append(temp)

    people_by_symptom = []
    people_key = []
    for s in symptoms:

ECO/templates/ECO/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <title>ECO Health</title>

    <link rel="stylesheet" href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
    <div class="container">

    <div class="row clearfix">
        <div class="col-md-12 column">
            <nav class="navbar navbar-default navbar-inverse" role="navigation">
                <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                    <a class="navbar-brand" href="{% url 'ECO:index' %}">Eco-Health</a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li id="index">
                             <a href="{%  url 'ECO:index' %}">首页</a>
                        </li>
                        <li id="disease">
                             <a href="{%  url 'ECO:disease_index' %}">疾病</a>
                        </li>
                        <li id="symptom">
                             <a href="{%  url 'ECO:symptom_index' %}">症状</a>
                        </li>
                        <li id="treatment">
                             <a href="{%  url 'ECO:treatment_index' %}">治疗手段</a>
                        </li>
                        <li id="person">
                             <a href="{%  url 'ECO:person_index' %}">个人主页</a>
                        </li>
                        <li id="social">
                             <a href="{%  url 'ECO:social_index' %}">社交</a>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" />
                        </div> <button type="submit" class="btn btn-default">搜索</button>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li>
                             <a href="{% url 'ECO:user_logout' %}" class="btn bt" data-toggle="modal">注销</a>
                        </li>
                        {% else %}
                        <li>
                             <a href="#login_modal" class="btn bt" data-toggle="modal">登录</a>
                        </li>
                        <li>
                             <a href="#register_modal" class="btn bt" data-toggle="modal">注册</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>

            </nav>

            {% block index_image %}

            {% endblock %}
        </div>
    </div>

    {% block index %}
    <div class="row clearfix">
        <div class="col-md-3 column">
            {% block list %}

            {% endblock %}
        </div>
        <div class="col-md-9 column">
            {% block content %}

            {% endblock %}
        </div>
    </div>
    {% endblock %}

    </div>

    <div id="login_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
        <div class="modal-content text-center">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">用户登录</h4>
            </div>
            <div class="modal-body">
                <form id="user_login_form" class="form-horizontal" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username" class="col-sm-2 control-label">用户名</label>
                        <div class="col-sm-10">
                            <input id="username" type="text" class="form-control" name="username">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="password" class="col-sm-2 control-label">密码</label>
                        <div class="col-sm-10">
                            <input id="password"  type="password" class="form-control" name="password">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-10">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="remember_me" checked> 记住我
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-10">
                            <button id="user_login" type="button" class="btn btn-default">登录</button>
                        </div>
                    </div>
                </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
          </div>
        </div>
      </div>
    </div>

    <div id="register_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">用户注册</h4>
            </div>
            <div class="modal-body">
                <form id="user_register_form" class="form-horizontal" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username" class="col-sm-2 control-label">用户名</label>
                        <div class="col-sm-10">
                            <input id="username" type="text" class="form-control" name="username">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="email" class="col-sm-2 control-label">邮箱</label>
                        <div class="col-sm-10">
                            <input id="email" type="email" class="form-control" name="email">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="password" class="col-sm-2 control-label">密码</label>
                        <div class="col-sm-10">
                            <input id="password"  type="password" class="form-control" name="password">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="check_password" class="col-sm-2 control-label">确认密码</label>
                        <div class="col-sm-10">
                            <input id="check_password"  type="password" class="form-control" name="check_password">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="age" class="col-sm-2 control-label">年龄</label>
                        <div class="col-sm-10">
                            <input id="age"  type="text" class="form-control" name="age">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="area" class="col-sm-2 control-label">地区</label>
                        <div class="col-sm-10">
                            <input id="area" type="text" class="form-control" name="area">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="sex" class="col-sm-2 control-label">性别</label>
                        <div class="col-sm-10">
                            <input id="sex" type="text" class="form-control" name="sex">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-4 col-sm-8">
                            <button id="user_register" type="button" class="btn btn-default">注册</button>
                        </div>
                    </div>
                </form>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
          </div>
        </div>
      </div>
    </div>

    <div id="register_feedback_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
        <div class="modal-content text-center">
            <div class="modal-body">
                <div class="align-items-center">
                    <h1 class="text-primary">注册成功!</h1>
                </div>
                <div class="align-items-center">
                    <button id="login_after_register" type="button" class="btn btn-default">登录</button>
                </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
          </div>
        </div>
      </div>
    </div>

    <div id="info_feedback_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
        <div class="modal-content text-center">
            <div class="modal-body">
                <div class="align-items-center">
                    <h1 class="text-primary"></h1>
                </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
          </div>
        </div>
      </div>
    </div>

    <script>
        $(document).ready(function () {
            $('#user_login').on('click', function () {
                let user_info = $('#user_login_form').serialize();
                $.ajax({
                    url: "{% url 'ECO:user_login' %}",
                    type: "post",
                    datatype: "json",
                    data: user_info,
                    async: false,
                    success: function(ret) {
                        if(ret.status === "success")
                            window.location = '{% url 'ECO:index' %}';
                        else if(ret.error_message === "user_not_exist")
                        {
                            $('#user_login_form').find('input').each(function () {$(this).val("");});
                            $('#info_feedback_modal').modal('show').find('h1').eq(0).text("用户不存在");
                        }
                        else
                        {
                            $('#user_login_form').find('input').each(function () {$(this).val("");});
                            $('#info_feedback_modal').modal('show').find('h1').eq(0).text("密码不正确");
                        }
                    }
                })
            });

            $('#user_register').on('click', function(){
                let user_info = $('#user_register_form').serialize();
                $.ajax({
                    url:"{% url 'ECO:user_register' %}",
                    type: "post",
                    datatype: "json",
                    data: user_info,
                    async: false,
                    success: function(ret) {
                        if(ret.status === "success"){
                            $('#user_register_form').find('input').each(function () {$(this).val("");});
                            $('#register_modal').modal('hide');
                            $('#register_feedback_modal').modal('show');
                        }
                        else
                        {
                            $('#info_feedback_modal').modal('show').find('h1').eq(0).text("用户名已经存在");
                            $('#user_register_form').find('input').each(function () {$(this).val("");});
                        }
                    }
                })
            });

            $('#login_after_register').on('click', function () {
                $('#login_modal').modal('show');
                $('#register_feedback_modal').modal('hide');
            })
        });
    </script>

</body>
</html>

ECO/templates/ECO/person_base.html
{% extends "ECO/base.html" %}

{% block list %}
    <div class="list-group">
        <a href="{% url 'ECO:person_disease' %}" class="list-group-item active"><h4>疾病概况</h4></a>
        <div class="list-group-item">
            <span class="badge">{{ counts.0 }}</span> <a href='{% url 'ECO:person_symptom' %}'><h4>常见症状</h4></a>
        </div>
        <div class="list-group-item">
            <span class="badge">{{ counts.1 }}</span> <a href='{% url 'ECO:person_treatment' %}'><h4>治疗手段</h4></a>
        </div>
        <div class="list-group-item">
            <a href='{% url 'ECO:person_info' %}'><h4>基础信息</h4></a>
        </div>
        <div class="list-group-item">
            <a href='{% url 'ECO:person_update' %}'><h4>每日更新</h4></a>
        </div>
        <a class="list-group-item active" href='{%  url 'ECO:person_diagram' %}'><h4>图表分析</h4></a>
    </div>
{% endblock %}

{% block content %}
    {% block main %}

    {% endblock %}
    <script>
    $(document).ready(function(){
        $('#person').addClass('active');
    });
    </script>
{% endblock %}

ECO/templates/ECO/person_diagram.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ECO/templates/ECO/social_base.html
{% extends 'ECO/base.html' %}

{% block list %}
    <div class="list-group">
        <a href="{% url 'ECO:social_friendstate' %}" class="list-group-item active"><h4>好友动态</h4></a>
        <div class="list-group-item">
            <span class="badge">{{ counts.0 }}</span> <a href='{% url 'ECO:social_friendlist' %}'><h4>关注列表</h4></a>
        </div>
        <div class="list-group-item">
            <span class="badge">{{ counts.0 }}</span> <a href='{% url 'ECO:social_sendstate' %}'><h4>发表动态</h4></a>
        </div>
        <div class="list-group-item">
            <span class="badge">{{ counts.1 }}</span> <a href='{% url 'ECO:social_newfriend' %}'><h4>发现</h4></a>
        </div>
        <a class="list-group-item active" href='{%  url 'ECO:social_heart' %}'><h4>爱心墙</h4></a>
    </div>
{% endblock %}

{% block content %}
    {% block main %}

    {% endblock %}
    <script>
    $(document).ready(function(){
        $('#social').addClass('active');
    });
    </script>
{% endblock %}